name: Create and publish a Docker image

on:
  workflow_dispatch:

  schedule:
    - cron: '11 00 1 * *'

  push:
    branches: [ "main" ]

env:
  owner: ${{ github.repository_owner }}
  repository: ${{ github.repository_owner }}/telegram-bot-api
  registry: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.registry }}
        username: ${{ env.owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.repository }}:${{ steps.date.outputs.date }},
          ${{ env.repository }}:latest,
          ${{ env.registry }}/${{ env.repository }}:${{ steps.date.outputs.date }},
          ${{ env.registry }}/${{ env.repository }}:latest

    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: ${{ steps.date.outputs.date }}
        generate_release_notes: true
